---
- name: apt-get update
  apt:
    update_cache: true
    autoclean: true
    autoremove: true
    cache_valid_time: 86400
    force: true
    force_apt_get: true
  become: true

- name: apt-get upgrade
  apt:
    upgrade: full
    autoclean: true
    autoremove: true
    force: true
    force_apt_get: true
  become: true

- name: apt-get dist-upgrade
  apt:
    upgrade: dist
    autoclean: true
    autoremove: true
    force: true
    force_apt_get: true
  become: true

- name: apt-get install 'man', 'vim' and 'nano' packages
  apt:
    name: [ 'man', 'vim', 'nano' ]
    state: present
    force: true
    force_apt_get: true
  become: true

- name: apt-get install additional packages
  apt:
    name: "{{ _additional_packages }}"
    state: present
    force: true
    force_apt_get: true
  become: true
  when: (_additional_packages | list | length > 0)
