---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: |
    not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
    and not inventory_hostname == ansible_hostname
  register: _hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_host }}.+$"
    line: "{{ ansible_host }} {{ inventory_hostname }} {{ inventory_hostname_short }}"
  register: _hostsfile

- name: Reboot
  shell: sleep 5 && reboot
  async: 1
  poll: 0
  when: _hostname['changed'] or _hostsfile['changed']

- name: Wait for Reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 180
  when: _hostname['changed'] or _hostsfile['changed']