---
- name: Ensure hostname set
  hostname:
    name: "{{ ansible_hostname }}"
  when: not ansible_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: _hostname

- debug:
    var: hostvars

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_host }}.+$"
    line: "{{ ansible_host }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: _hostsfile

- name:
  notify:
    - Reboot
