---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: >
    not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
    and not inventory_hostname == ansible_hostname
  register: _hostname

- name: Template /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    backup: true
  register: _hostsfile

- name: Reboot
  shell: sleep 5 && reboot
  async: 1
  poll: 0
  changed_when: false
  when: >
    _hostname['changed']
    or _hostsfile['changed']

- name: Wait for Reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 180
  when: >
    _hostname['changed']
    or _hostsfile['changed']