---
docker_package_name: docker-ce
  # debian | ubuntu | raspbian
  # https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-armhf/Packages
    # arm64, amd64, armhf, ppc64el, s390x
    # tag: 5:18.09.4~3-0~ubuntu-bionic
  # https://download.docker.com/linux/debian/dists/stretch/stable/binary-armhf/Packages
    # arm64, amd64, armhf, ppc64el
    # tag: 5:18.09.4~3-0~debian-stretch
  # https://download.docker.com/linux/raspbian/dists/stretch/stable/binary-armhf/Packages
    # arm64, amd64, armhf, ppc64el
    # tag: 5:18.09.4~3-0~raspbian-stretch

docker_pre_requisites: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'gpgv' ]
