---
- name: Install python before doing any other steps
  hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y update && sudo apt-get -y install python
      register: install_python
      changed_when: >
        not 'python is already the newest version' in install_python['stdout']

  post_tasks:
    - name: Next steps
      debug:
        msg: "Python has now been installed successfully. You are ready to proceed with the next playbook."
