---
- name: Setup all hosts with static IPs
  hosts: targets
  pre_tasks:
    - name: Output general host and OS details
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ansible_hostname }} | {{ inventory_hostname }} | {{ inventory_hostname_short }} | {{ ansible_host }}"
        - "{{ os_family }} | {{ os_distro }} | {{ os_codename }} | {{ target_node_arch }}"
  
  post_tasks:
    - name: Next steps
      debug:
        msg: "Please confirm that all devices successfully negotiated their respective static IPs. Now execute the next playbook."

  roles:
    - role: prerequisites
    - role: mvrahden/networking-setup
      subtasks: [ 'interfaces' ]
      networking_device_interfaces: "{{ _networking_device_interfaces }}"
      networking_interface_profiles: "{{ _networking_interface_profiles }}"
