- name: Install python before doing any other steps
  hosts: targets
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y update && sudo apt-get -y install python
      register: install_python
      changed_when: >
        not 'python is already the newest version' in install_python['stdout']

##### keep these plays separated because of fact gathering #####

- name: Setup all hosts with the following roles
  hosts: targets
  pre_tasks:
    - name: Output general host and OS details
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ansible_hostname }} | {{ inventory_hostname }} | {{ inventory_hostname_short }} | {{ ansible_host }}"
        - "{{ os_family }} | {{ os_distro }} | {{ os_codename }} | {{ target_node_arch }}"
  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoclean: yes
        autoremove: yes
  roles:
    - role: prerequisites
    - role: mvrahden/networking-setup
      subtasks: [ 'interfaces' ]
      networking_domain: "{{ group_primary_domain }}"
      networking_interface_profiles: "{{ networking_interface_profiles }}"
    - role: mvrahden/apt-cacher-ng
      apt_cacher_server: "{{ apt_cacher_cache_server | default(None) or groups['targets'][0] }}"
      enable_apt_caching: true
    - role: mvrahden/ntp
    - role: mvrahden/ssh
    - role: mvrahden/switch-off-interfaces
    - role: mvrahden/swapfile
    - role: pip
    - role: docker
