---
- name: Setup all hosts with the following roles
  hosts: targets
  pre_tasks:
    - name: Wait for successful connection
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 180

    - name: Output general host and OS details
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ansible_hostname }} | {{ inventory_hostname }} | {{ inventory_hostname_short }} | {{ ansible_host }}"
        - "{{ os_family }} | {{ os_distro }} | {{ os_codename }} | {{ target_node_arch }}"
  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoclean: yes
        autoremove: yes

  roles:
    - role: mvrahden/networking-setup
      subtasks: [ 'hostname' ]
    - role: mvrahden/apt-cacher-ng
    - role: mvrahden/ntp
    - role: mvrahden/ssh
    - role: mvrahden/switch-off-interfaces
    - role: mvrahden/swapfile
    - role: pip
    - role: docker
