---
- name: Setup all hosts with the following roles
  hosts: targets
  pre_tasks:
    - name: Output general host and OS details
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ansible_hostname }} | {{ inventory_hostname }} | {{ inventory_hostname_short }} | {{ ansible_host }}"
        - "{{ os_family }} | {{ os_distro }} | {{ os_codename }} | {{ target_node_arch }}"
  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoclean: yes
        autoremove: yes

    - role: networking-setup
      subtasks: [ 'hostname' ]
      networking_domain: "{{ group_primary_domain }}"
      networking_device_interfaces: "{{ networking_interfaces }}"
    - role: mvrahden/apt-cacher-ng
      apt_cacher_server: "{{ apt_cacher_cache_server | default(None) or groups['targets'][0] }}"
      enable_apt_caching: true
    - role: mvrahden/ntp
    - role: mvrahden/ssh
    - role: mvrahden/switch-off-interfaces
    - role: mvrahden/swapfile
    - role: pip
    - role: docker
